### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by martinbrylski** [rosenpin/i3-agenda#46]
Under current Manjaro/i3 I get this (possible) python dependency error while executing i3agenda:

```
Traceback (most recent call last):
  File "/usr/bin/i3-agenda", line 33, in <module>
    sys.exit(load_entry_point('i3-agenda==1.3', 'console_scripts', 'i3-agenda')())
  File "/usr/bin/i3-agenda", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: i3-agenda
```

I hope you can help

**Comment by rosenpin** [comment]
I ran into the same issue, it's most likely because you updated your python package to 3.9

You don't have i3-agenda installed for python3.9 

You need to either  
1. reinstall it using the appropriate pip version
2. reinstall python 3.8

**Comment by martinbrylski** [comment]
Thx. That helped 👍
