### ISSUE TITLE
Token revoked

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/i3-agenda#52]
```
Traceback (most recent call last):
  File "/usr/bin/i3-agenda", line 33, in <module>
    sys.exit(load_entry_point('i3-agenda==1.4', 'console_scripts', 'i3-agenda')())
  File "/usr/lib/python3.9/site-packages/i3_agenda-1.4-py3.9.egg/i3_agenda/__init__.py", line 99, in main
  File "/usr/lib/python3.9/site-packages/i3_agenda-1.4-py3.9.egg/i3_agenda/__init__.py", line 273, in connect
  File "/home/tomer/.local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "/home/tomer/.local/lib/python3.9/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/tomer/.local/lib/python3.9/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/tomer/.local/lib/python3.9/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
```

If you revoked the token, or it was automatically revoked for some reason, you will need to re-initialize it

**Comment by rosenpin** [comment]
## Solution:
`rm  ~/.i3agenda/i3agenda_google_token.pickle`  
`i3-agenda -c ~/.google_credentials.json`  
Your browser should open, grant access to your account, that's it
