### ISSUE TITLE
i3agenda_google_token.pickle not found

### ISSUE THREAD

**Issue by albert-ying** [rosenpin/i3-agenda#70]
Hi, I followed the instruction and encountered the following error after I authorize it in the browser. Could you help me with it? Thank you!

```
❯ i3-agenda -c ~/client_secret_googleusercontent.com.json
Please visit this URL to authorize this application: https://accounts.google.com/.....

Traceback (most recent call last):
  File "/Users/A.Y/miniconda3/bin/i3-agenda", line 8, in <module>
    sys.exit(main())
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/i3_agenda/__init__.py", line 42, in main
    events = load_events(args)
  File "/Users/A.Y/miniconda3/lib/python3.8/site-packages/i3_agenda/__init__.py", line 33, in load_events
    events = get_events(args.credentials, args.ids, args.maxres, args.today)
  File "/Users/A.Y/miniconda3/bin/API.py", line 121, in get_events
    service = connect(credentials)
  File "/Users/A.Y/miniconda3/bin/API.py", line 19, in connect
    creds = get_credentials(credspath)
  File "/Users/A.Y/miniconda3/bin/API.py", line 47, in get_credentials
    with open(TMP_TOKEN, "wb") as token:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/A.Y/.i3agenda/i3agenda_google_token.pickle'
```

**Comment by rosenpin** [comment]
What's the output for `ls ~/.i3agenda`?

**Comment by rosenpin** [comment]
try to mkdir the .i3agenda directory manually  
`mkdir ~/.i3agenda`

Do you get a browser popup when you run `i3-agenda -c ~/client_secret_googleusercontent.com.json`?

**Comment by albert-ying** [comment]
> mkdir ~/.i3agenda

This solved my problem.

Thank you!
