### ISSUE TITLE
module 'pyparsing' has no attribute 'downcaseTokens'

### ISSUE THREAD

**Issue by Zackhardtoname** [rosenpin/i3-agenda#77]
I think maybe my Arch upgraded the package too forward and broke a dependency.

```
Downloads i3-agenda -c /home/zack/drive/else/Configs/google_calendar_credentials.json -ttl 10     
Traceback (most recent call last):
  File "/usr/bin/i3-agenda", line 33, in <module>
    sys.exit(load_entry_point('i3-agenda==1.6.3', 'console_scripts', 'i3-agenda')())
  File "/usr/lib/python3.9/site-packages/i3_agenda/__init__.py", line 59, in main
    events = load_events(args)
  File "/usr/lib/python3.9/site-packages/i3_agenda/__init__.py", line 39, in load_events
    from API import get_events
  File "/usr/bin/API.py", line 9, in <module>
    from googleapiclient.discovery import build, Resource
  File "/usr/lib/python3.9/site-packages/googleapiclient/discovery.py", line 42, in <module>
    import httplib2
  File "/usr/lib/python3.9/site-packages/httplib2/__init__.py", line 52, in <module>
    from . import auth
  File "/usr/lib/python3.9/site-packages/httplib2/auth.py", line 20, in <module>
    auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'

```

**Comment by Zackhardtoname** [comment]
I rebuilt the package via reinstallation. Thanks!
